[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.116.1",
    "netmiko>=4.4.0",
    "scrapli>=2024.7.30.post1",
    "textfsm>=1.1.3",
    "uvicorn>=0.33.0",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
core = { workspace = true }

[dependency-groups]
dev = [
    "core",
]
