# Tom Smykowski Core Service Configuration
# YAML version of core-related settings from local.env.example

# Core Service Settings
host: "0.0.0.0"
port: 8000
log_level: "info"
project_root: "../../../.."

# Redis Configuration
redis_host: "localhost"  # would be 'redis' when running in docker compose
redis_port: 6379

# Authentication
allow_inline_credentials: true  # good to keep this False when there are better options
auth_mode: "api_key"
api_key_headers: ["X-API-Key", "api-key"]
api_keys: ["abc123:admin", "asldfjaldkf:admin"]

# Inventory Configuration
inventory_type: "yaml"  # or "swis"
inventory_file: "inventory/inventory.yml"

# SolarWinds SWIS/SWAPI Configuration
swapi_host: "solarwinds.example.com"
swapi_port: 17774
swapi_username: "swapi_user"
swapi_password: "swapi_pw"
swapi_default_cred_name: "autoUser"

# SolarWinds Device Mappings - processed in order, first match wins
swapi_device_mappings:
  - match:
      vendor: "cisco"
      description: "asr"
    action:
      adapter: "scrapli"
      adapter_driver: "cisco_iosxe"
      credential_id: "cisco_creds"
      port: 22
  - match:
      vendor: "arista"
    action:
      adapter: "scrapli" 
      adapter_driver: "arista_eos"
      credential_id: "arista_creds"
  - match:
      vendor: "cisco"
    action:
      adapter: "netmiko"
      adapter_driver: "cisco_ios"
      credential_id: "cisco_creds"
  # Default catch-all rule (matches everything)
  - match:
      vendor: ".*"
    action:
      adapter: "netmiko"
      adapter_driver: "cisco_ios"
